# Generated by Django 3.2.3 on 2021-05-21 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='name')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='phone')),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('user_type', models.CharField(blank=True, choices=[('none', 'NONE'), ('challenged', 'CHALLENGED'), ('pregnant', 'PREGNANT'), ('infant_companion', 'INFANT_COMPANION'), ('child', 'CHILD')], default='none', help_text='유저 타입', max_length=20)),
                ('challenged_type', models.CharField(blank=True, max_length=50)),
                ('protector_type', models.CharField(blank=True, choices=[('none', 'NONE'), ('family', 'FAMILY'), ('sibling', 'SIBLING'), ('relative', 'RELATIVE'), ('friend', 'FRIEND'), ('lover', 'LOVER'), ('etc', 'ETC')], default='none', help_text='보호자 타입', max_length=20)),
                ('protector_phone', models.CharField(blank=True, max_length=12)),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
