# Generated by Django 3.2.3 on 2021-05-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenged_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='protector_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='protector_type',
            field=models.CharField(blank=True, choices=[('none', 'NONE'), ('family', 'FAMILY'), ('sibling', 'SIBLING'), ('relative', 'RELATIVE'), ('friend', 'FRIEND'), ('lover', 'LOVER'), ('etc', 'ETC')], default='none', help_text='보호자 타입', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('none', 'NONE'), ('challenged', 'CHALLENGED'), ('pregnant', 'PREGNANT'), ('infant_companion', 'INFANT_COMPANION'), ('child', 'CHILD')], default='none', help_text='유저 타입', max_length=20),
        ),
    ]
