# Generated by Django 3.2.3 on 2021-05-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210522_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('none', 'NONE'), ('challenged', 'CHALLENGED'), ('pregnant', 'PREGNANT'), ('infant_companion', 'INFANT_COMPANION'), ('child', 'CHILD'), ('old', 'OLD')], default='none', help_text='유저 타입', max_length=20),
        ),
    ]
