# Generated by Django 3.2.3 on 2021-05-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='protector_type',
            field=models.CharField(blank=True, help_text='보호자 타입', max_length=20),
        ),
    ]
