# Generated by Django 3.2.3 on 2021-05-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point_longitude', models.CharField(blank=True, max_length=12)),
                ('end_point_longitude', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
