# Generated by Django 3.2.3 on 2021-05-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_reservation_finished',
            field=models.BooleanField(default=False),
        ),
    ]
