# Generated by Django 3.2.3 on 2021-05-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20210522_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='actual_texi_fare',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_point',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='expected_texi_fare',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='requirement_information',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_point',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
